// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_fWSllPiZT6pv-ifo9qjaS_4X1ObK4aY',
    appId: '1:954155866715:web:ce8790d60ec51bfad07d7e',
    messagingSenderId: '954155866715',
    projectId: 'busy-bee-a55ef',
    authDomain: 'busy-bee-a55ef.firebaseapp.com',
    storageBucket: 'busy-bee-a55ef.appspot.com',
    measurementId: 'G-KNLT6KHL0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuPX0ZIjL9HWEoYId-lNYFtGCOppL21f4',
    appId: '1:954155866715:android:d6f36ae6a7997413d07d7e',
    messagingSenderId: '954155866715',
    projectId: 'busy-bee-a55ef',
    storageBucket: 'busy-bee-a55ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYf91p9943L77-qkfxPhlEmk4a4VO-iBQ',
    appId: '1:954155866715:ios:9531d1e11de7d776d07d7e',
    messagingSenderId: '954155866715',
    projectId: 'busy-bee-a55ef',
    storageBucket: 'busy-bee-a55ef.appspot.com',
    iosBundleId: 'com.example.busyBee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYf91p9943L77-qkfxPhlEmk4a4VO-iBQ',
    appId: '1:954155866715:ios:e9d2abfc61b7afe7d07d7e',
    messagingSenderId: '954155866715',
    projectId: 'busy-bee-a55ef',
    storageBucket: 'busy-bee-a55ef.appspot.com',
    iosBundleId: 'com.example.busyBee.RunnerTests',
  );
}
